name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_release_tag.outputs.release_tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Get Release Tag
        id: set_release_tag
        run: |
          TAG="v$(date -u +'%Y%m%d%H%M%S')"
          echo "release_tag=${TAG}" >> $GITHUB_OUTPUT

  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: windows-latest
            goos: windows
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
          GOEXE: ${{ matrix.goos == 'windows' && '.exe' || '' }}
        run: |
          echo "Building for $GOOS/$GOARCH..."
          mkdir -p dist/${GOOS}-${GOARCH}
          GOOS=$GOOS GOARCH=$GOARCH go build -o dist/${GOOS}-${GOARCH}/test_media_generator$GOEXE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_media_generator-${{ matrix.goos }}-${{ matrix.arch }}
          path: dist/${GOOS}-${GOARCH}

  release:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.test.outputs.release_tag }}
          name: Release ${{ needs.test.outputs.release_tag }}
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/**/test_media_generator*
          asset_name: ${{ basename }}
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
