name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Build Binaries
        env:
          CGO_ENABLED: 0
        run: |
          # Set the output directory
          OUTPUT_DIR="dist"
          mkdir -p $OUTPUT_DIR

          # List of platforms to build for
          PLATFORMS=(
              "windows/amd64"
              "darwin/amd64"
              "darwin/arm64"
              "linux/amd64"
              "linux/arm64"
          )

          # Build the project for each platform
          for PLATFORM in "${PLATFORMS[@]}"; do
              OS=$(echo $PLATFORM | cut -d'/' -f1)
              ARCH=$(echo $PLATFORM | cut -d'/' -f2)
              OUTPUT_NAME="test_media_generator"

              if [ "$OS" = "windows" ]; then
                  OUTPUT_NAME+=".exe"
              fi

              echo "Building for $OS/$ARCH..."

              # Set environment variables for cross-compilation
              GOOS=$OS GOARCH=$ARCH go build -o $OUTPUT_DIR/$OS-$ARCH/$OUTPUT_NAME

              if [ $? -ne 0 ]; then
                  echo "An error occurred while building for $OS/$ARCH."
                  exit 1
              fi
          done

          echo "Builds completed successfully."

      - name: Archive Binaries
        run: |
          cd dist
          for PLATFORM in *; do
            zip -r ${PLATFORM}.zip $PLATFORM
          done
          cd ..

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/*.zip

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v$(date -u +'%Y%m%d%H%M%S')
          name: Release v$(date -u +'%Y%m%d%H%M%S')
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.zip
          asset_name: ${{ basename }}
          asset_content_type: application/zip
